version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.13
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./volumes/full-stack/zoo1/data:/data
      - ./volumes/full-stack/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_PROTOCOL_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/full-stack/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  graphite:
    image: sitespeedio/graphite
    ports:
      - "2003:2003"
      - "2004:2004"
      - "8080:80"
    volumes:
      - ./volumes/full-stack/graphite/storage/whisper:/opt/graphite/storage/whisper

  grafana:
    image: grafana/grafana
    volumes:
      - ./volumes/full-stack/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - graphite

  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - graphite

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - graphite
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
